### ISSUE TITLE
Most oversight reports not being delivered`

### ISSUE THREAD

**Issue by konklone** [sunlightlabs/scout#511]
Most [GAO and IG reports](https://scout.sunlightfoundation.com/search/documents/*) aren't being emailed to me, as of at least late May, when I first noticed and privately reported this bug.

**Comment by konklone** [comment]
It looks like the last IG report I got delivered to me from my `*` wildcard alert is on June 20th.

**Comment by crdunwel** [comment]
I've looked into the issue briefly but couldn't identify the problem. Do you know if it's just your account that is experiencing the issue? Also if you could direct me to pain points in the code where an error like this may be happening then I'll take another look.

**Comment by crdunwel** [comment]
@konklone did this spontaneously resolve itself?
